#!/bin/bash
echo "========== V81 多维度检查报告 =========="
echo ""
echo "【维度1】代码结构层检查"
echo "---"
echo "文件总行数: $(wc -l < index.html)"
echo "  <script>标签: $(grep -c '<script>' index.html)"
echo "  </script>标签: $(grep -c '</script>' index.html)"
echo "  </html>标签: $(grep -c '</html>' index.html)"
echo ""
echo "【维度2】JavaScript函数定义检查"
echo "---"
FUNC_COUNT=$(grep -oP 'function \K\w+' index.html | sort -u | wc -l)
echo "定义的函数数量: $FUNC_COUNT"
echo ""
echo "【维度3】事件交互层检查"
echo "---"
echo "onclick事件数量: $(grep -oc 'onclick=' index.html)"
echo "addEventListener数量: $(grep -oc 'addEventListener' index.html)"
echo ""
echo "【维度4】错误处理检查"
echo "---"
echo "try-catch块数量: $(grep -c 'try {' index.html)"
echo "localStorage操作: $(grep -c 'localStorage' index.html)"
echo ""
echo "【维度5】用户体验检查"
echo "---"
echo "showToast调用: $(grep -c "showToast" index.html)"
echo "alert调用: $(grep -c "alert(" index.html)"
echo ""
echo "【维度6】版本信息检查"
echo "---"
echo "当前版本: $(grep -oP '(?<=<title>).*(?=</title>)' index.html)"
echo "========== 检查完成 =========="
